name: Build Deadshot

on:
  push:
    tags:
      - 'v*'   # build when you push a tag like v1.0.0
  workflow_dispatch: # allow manual trigger

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install:all

      - name: Build Deadshot
        run: npm run build